[package]
name = "cjs_world"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.12.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "multi-threaded",
    "png",
]

[dependencies]
bevy_egui = "0.24.0"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
