[package]
name = "cjs_whole_new_world"
version = "0.0.1"
edition = "2021"

[dependencies.bevy]
version = "0.12.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "bevy_render",
    "bevy_pbr",
    "tonemapping_luts",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "multi-threaded",
    "png",
]

[dependencies]
bitvec = "1.0.1"
bevy_egui = "0.24.0"
leafwing-input-manager = "0.11.2"
noise = "0.8.2"
log = "0.4.20"

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
